spring.application.name=payment-service

spring.datasource.url=jdbc:postgresql://postgres:5432/paymentdb
spring.datasource.username=postgres
spring.datasource.password=123456

#security config
#spring.security.user.name=sshettyan
#spring.security.user.password=Qwerty123

jwt.secertKey = sdfgbhnjwsedrftgyhujdcfvgbhnjmwsedrftgyhjxdcfvgbh

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# kafka
spring.kafka.bootstrap-servers=kafka:9092

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.producer.properties.spring.json.add.type.headers=false

#spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Consumer
spring.kafka.consumer.group-id=payment-group-New
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.value.default.type=com.payment.dto.FraudResultEvent

